### ISSUE TITLE
pyavm can't parse a cd matrix? 

### ISSUE THREAD

**Issue by augustfly** [astrofrog/pyavm#22]
hi,

i have a fits file (header only) that i'm trying to import to pyavm through 

```
header = fits.getheader("file.txt")
avm = AVM.from_header(header)
```

The header contains a CD matrix, but the output avm.Spatial.Scale is not reflecting this. As far as I can tell from the code, pyavm should be finding and converting the CD matrix, but it isn't or maybe I am mistaken. 

The header is at: https://gist.github.com/augustfly/9620005

Below is a screen shot of warnings issued by pyavm that I simply don't understand. 

![warnings_pyavm](https://f.cloud.github.com/assets/234283/2448221/c2877f86-aea3-11e3-99c0-1c5aaf32e54e.png)

**Comment by astrofrog** [comment]
@augustfly I've now fixed this properly including determining Rotation from the CD matrix in #34
